# Generated by Django 5.0.3 on 2024-03-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokobuku', '0002_carts_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('cust_name', models.CharField(max_length=200)),
                ('cust_email', models.EmailField(max_length=200)),
                ('cust_review', models.TextField(max_length=500)),
            ],
        ),
    ]
